# -*- coding: utf-8 -*-
"""poo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gY0F4ixIWOrlPfiYeCxvxHtzQB3ALv_7
"""

"""
    Script para explicar los conceptos básicos de POO
    Concepto: Los objetos son instancias de clases
    Codigo que muestra el paradigma de la POO usando Python
"""

######## Definición de la clase ###############################################
class Coche:
# Acá se definen las variables o características privadas de la clase
    def __init__(self, color, marca, kmrecorridos): # Este es el constructor de la clase
        self.color = color
        self.marca = marca
        self.kmrecorridos = kmrecorridos

# Acá se definen los métodos o funciones de la clase
    def mostrar(self):
        print('\nEl coche es {}'.format(self.marca))
        print('El color del coche es {}'.format(self.color))
        print('El kilometraje es {}'.format(self.kmrecorridos))

########## Fin de la definición de la clase ###################################


# Acá se definen las instancias u objetos de la clase
coche1 = Coche("Blanco", "Audi", "30")
coche2 = Coche("Rojo", "Ferrari", "110")
coche3 = Coche("Azul","Renault", "550")

# Se aplican métodos o funciones definidas en la clase
coche1.mostrar()
coche3.mostrar()
coche2.mostrar()

# Acá se borran los objetos una vez que han sido usados
del coche2, coche3, coche1